/* eslint-disable react/no-unescaped-entities */
import Head from "next/head";
import Image from "next/image";
import imageLoader from "../imagesLoader";
import img from "../public/house.jpg";
import styles from "../styles/Home.module.css";

const Home = () => {
return (
    <div className={styles.container}>
      <Head>
        <title>O'Paradis</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        <section className={styles.section_up}>
          <Image
            loader={imageLoader}
            unoptimized
            src={img}
            priority
            alt="image house"
          />
        </section>
        <section className={styles.section_middle}>
        <article className={styles.card}>
            <div className={styles.card_img}>image</div>
            <div className={styles.card_text}>
              <h2 className={styles.card_text__name}>maison 1</h2>
              <p>Type du logement</p>
              <div className={styles.card_text__location}>
                <p>Ville</p>
                <p>Pays</p>
              </div>
              <p>Date de création</p>
            </div>
          </article>          
          <article className={styles.card}>
            <div className={styles.card_img}>image</div>
            <div className={styles.card_text}>
              <h2 className={styles.card_text__name}>maison 2</h2>
              <p>Type du logement</p>
              <div className={styles.card_text__location}>
                <p>Ville</p>
                <p>Pays</p>
              </div>
              <p>Date de création</p>
            </div>
          </article>          
          <article className={styles.card}>
            <div className={styles.card_img}>image</div>
            <div className={styles.card_text}>
              <h2 className={styles.card_text__name}>maison 3</h2>
              <p>Type du logement</p>
              <div className={styles.card_text__location}>
                <p>Ville</p>
                <p>Pays</p>
              </div>
              <p>Date de création</p>
            </div>
          </article>
          <article className={styles.card}>
            <div className={styles.card_img}>image</div>
            <div className={styles.card_text}>
              <h2 className={styles.card_text__name}>maison 4</h2>
              <p>Type du logement</p>
              <div className={styles.card_text__location}>
                <p>Ville</p>
                <p>Pays</p>
              </div>
              <p>Date de création</p>
            </div>
          </article>
        </section>
        <section className={styles.section_down}>
          <article className={styles.section_down__article}>
            <Image
            loader={imageLoader}
            unoptimized
            width="350"
            height="350"
            src="https://res.cloudinary.com/dhwbw94lc/image/upload/v1655197687/image%20zen/zen1_etri1e.png"
            alt="image cherche sa destination" />
            <p>1. Chercher sa destination</p>
          </article>
          <article className={styles.section_down__article}>
            <Image
            loader={imageLoader}
            unoptimized
            width="350"
            height="350"
            src="https://res.cloudinary.com/dhwbw94lc/image/upload/v1655197687/image%20zen/zen2_t8dl4l.png"
            alt="image choisir sa destination" />
            <p>2. Choisir sa destination</p>
          </article>
          <article className={styles.section_down__article}>
            <Image
            loader={imageLoader}
            unoptimized
            width="350"
            height="350"
            src="https://res.cloudinary.com/dhwbw94lc/image/upload/v1655197687/image%20zen/zen3_v86oux.png"
            alt="image profiter de votre destination" />
            <p>3. Profiter de votre destination</p>
          </article>
        </section>
      </div>
    </div>
  );
};

export default Home;
