export const ArrayAnimal = [
  {
    id: 1,
    src: "https://res.cloudinary.com/dhwbw94lc/image/upload/v1658828072/samples/animals/g9ltcevkludqfwp1monj.jpg",
    type: "Légendaire",
    race: "Chimére",
    maladie: "schizophrénie",
    notes: "lorem aopjdij dgnuon nufdguu fun ufngu gnf dug onu ufnguo d.",
  },
  {
    id: 2,
    src: "https://res.cloudinary.com/dhwbw94lc/image/upload/v1643711471/samples/animals/three-dogs.jpg",
    type: "Chien",
    race: "Bulldog",
    maladie: "RAS",
    notes: "lorem aopjdij dgnuon nufdguu fun ufngu gnf dug onu ufnguo d.",
  },
  {
    id: 3,
    src: "https://res.cloudinary.com/dhwbw94lc/image/upload/v1643711465/samples/animals/cat.jpg",
    type: "Chat",
    race: "Serval",
    maladie: "RAS",
    notes: "lorem aopjdij dgnuon nufdguu fun ufngu gnf dug onu ufnguo d.",
  },
  {
    id: 4,
    src: "",
    type: "Poisson",
    race: "Saumon",
    maladie: "RAS",
    notes: "lorem aopjdij dgnuon nufdguu fun ufngu gnf dug onu ufnguo d.",
  },
  {
    id: 5,
    src: "https://res.cloudinary.com/dhwbw94lc/image/upload/v1643711468/samples/sheep.jpg",
    type: "Mouton",
    race: "",
    maladie: "RAS",
    notes: "lorem aopjdij dgnuon nufdguu fun ufngu gnf dug onu ufnguo d.",
  },
  {
    id: 6,
    src: "",
    type: "Chevre",
    race: "Nain",
    maladie: "RAS",
    notes: "",
  },
  {
    id: 7,
    src: "https://res.cloudinary.com/dhwbw94lc/image/upload/v1658828170/samples/animals/nqfcqouzpqdueoemji3k.jpg",
    type: "Dragon",
    race: "feu",
    maladie: "RAS",
    notes: "lorem aopjdij dgnuon nufdguu fun ufngu gnf dug onu ufnguo d.",
  },
];

export const ArrayPlant = [
  {
    id:  1,
    src: "https://res.cloudinary.com/dhwbw94lc/image/upload/v1658828317/samples/plant/fcgkmcpry9k2rj3mbrgp.jpg",
    type: "Carnivore",
    notes: "Manger deux moutons par semaine et un grand verre d'eau plate.",
  },
  {
    id:  2,
    src: "https://res.cloudinary.com/dhwbw94lc/image/upload/v1658828403/samples/plant/hvj7qwuks9kv952ichmm.jpg",
    type: "Rosier",
    notes: "lorem aopjdij dgnuon nufdguu fun ufngu gnf dug onu ufnguo d.",
  },
  {
    id:  3,
    src: "",
    type: "Persil",
    notes: "RAS",
  },
  {
    id:  4,
    src: "https://res.cloudinary.com/dhwbw94lc/image/upload/v1658828481/samples/plant/vfpaebgaocymdtvxwdjr.jpg",
    type: "Tomate",
    notes: "RAS",
  },
];

export const arrayHouses = [
  {
    id: 'cl63lvh5k1967r2v27nv6g4fo',
    address: '27 Chemin de Saint-Laurent le Vieux',
    zipcode: '54700',
    city: 'Maidières',
    title: "Une belle région pleine d'Histoire",
    created_at: '27 Jul 2022',
    user_id: 'cl63lvh181883r2v2zifq6e28',
    country_id: 'cl63lvfj20518r2v2h5k5zkzk',
    type_id: 'cl63lvgtt1764r2v2zwvg6kfe',
    photo: [ [Object], [Object], [Object], [Object] ],
    type: { id: 'cl63lvgtt1764r2v2zwvg6kfe', type: 'Chateau' },
    country: { id: 'cl63lvfj20518r2v2h5k5zkzk', country: 'France' },
  },
  {
    id: 'cl63lvh581960r2v2z7osd7om',
    address: '3 Chemin des Pins',
    zipcode: '17100',
    city: 'Les Gonds',
    title: 'La ferme à la campagne',
    created_at: '27 Jul 2022',
    user_id: 'cl63lvh0l1876r2v2bf31e8lz',
    country_id: 'cl63lvfj20518r2v2h5k5zkzk',
    type_id: 'cl63lvgtt1764r2v2zwvg6kfe',
    photo: [],
    type: { id: 'cl63lvgtt1764r2v2zwvg6kfe', type: 'Chateau' },
    country: { id: 'cl63lvfj20518r2v2h5k5zkzk', country: 'France' },
  },
  {
    id: 'cl63lvh4x1953r2v21zab3orn',
    address: '1 Rue du Vert Bocage',
    zipcode: '76910',
    city: 'Criel-sur-Mer',
    title: 'Chez Ginette',
    created_at: '27 Jul 2022',
    user_id: 'cl63lvh021869r2v2fbuw6zf9',
    country_id: 'cl63lvfj20518r2v2h5k5zkzk',
    type_id: 'cl63lvgur1792r2v288uynrt1',
    photo: [],
    type: { id: 'cl63lvgur1792r2v288uynrt1', type: 'Hotel Privé' },
    country: { id: 'cl63lvfj20518r2v2h5k5zkzk', country: 'France' },
  },
  {
    id: 'cl63lvh4m1946r2v26pps2vhp',
    address: '1 Chemin du Clos de Bellevue',
    zipcode: '84190',
    city: 'Vacqueyras',
    title: 'Venez vous ressourcer chez nous',
    created_at: '27 Jul 2022',
    user_id: 'cl63lvgzj1862r2v240eesrnz',
    country_id: 'cl63lvfj20518r2v2h5k5zkzk',
    type_id: 'cl63lvgv01799r2v2db7sjwod',
    photo: [],
    type: { id: 'cl63lvgv01799r2v2db7sjwod', type: 'Mobile home' },
    country: { id: 'cl63lvfj20518r2v2h5k5zkzk', country: 'France' },
  }
]