export const ArrayAnimal = [
  {
    id: 1,
    src: "https://res.cloudinary.com/dhwbw94lc/image/upload/v1658828072/samples/animals/g9ltcevkludqfwp1monj.jpg",
    type: "Légendaire",
    race: "Chimére",
    maladie: "schizophrénie",
    notes: "lorem aopjdij dgnuon nufdguu fun ufngu gnf dug onu ufnguo d.",
  },
  {
    id: 2,
    src: "https://res.cloudinary.com/dhwbw94lc/image/upload/v1643711471/samples/animals/three-dogs.jpg",
    type: "Chien",
    race: "Bulldog",
    maladie: "RAS",
    notes: "lorem aopjdij dgnuon nufdguu fun ufngu gnf dug onu ufnguo d.",
  },
  {
    id: 3,
    src: "https://res.cloudinary.com/dhwbw94lc/image/upload/v1643711465/samples/animals/cat.jpg",
    type: "Chat",
    race: "Serval",
    maladie: "RAS",
    notes: "lorem aopjdij dgnuon nufdguu fun ufngu gnf dug onu ufnguo d.",
  },
  {
    id: 4,
    src: "",
    type: "Poisson",
    race: "Saumon",
    maladie: "RAS",
    notes: "lorem aopjdij dgnuon nufdguu fun ufngu gnf dug onu ufnguo d.",
  },
  {
    id: 5,
    src: "https://res.cloudinary.com/dhwbw94lc/image/upload/v1643711468/samples/sheep.jpg",
    type: "Mouton",
    race: "",
    maladie: "RAS",
    notes: "lorem aopjdij dgnuon nufdguu fun ufngu gnf dug onu ufnguo d.",
  },
  {
    id: 6,
    src: "",
    type: "Chevre",
    race: "Nain",
    maladie: "RAS",
    notes: "",
  },
  {
    id: 7,
    src: "https://res.cloudinary.com/dhwbw94lc/image/upload/v1658828170/samples/animals/nqfcqouzpqdueoemji3k.jpg",
    type: "Dragon",
    race: "feu",
    maladie: "RAS",
    notes: "lorem aopjdij dgnuon nufdguu fun ufngu gnf dug onu ufnguo d.",
  },
];

export const ArrayPlant = [
  {
    id:  1,
    src: "https://res.cloudinary.com/dhwbw94lc/image/upload/v1658828317/samples/plant/fcgkmcpry9k2rj3mbrgp.jpg",
    type: "Carnivore",
    notes: "Manger deux moutons par semaine et un grand verre d'eau plate.",
  },
  {
    id:  2,
    src: "https://res.cloudinary.com/dhwbw94lc/image/upload/v1658828403/samples/plant/hvj7qwuks9kv952ichmm.jpg",
    type: "Rosier",
    notes: "lorem aopjdij dgnuon nufdguu fun ufngu gnf dug onu ufnguo d.",
  },
  {
    id:  3,
    src: "",
    type: "Persil",
    notes: "RAS",
  },
  {
    id:  4,
    src: "https://res.cloudinary.com/dhwbw94lc/image/upload/v1658828481/samples/plant/vfpaebgaocymdtvxwdjr.jpg",
    type: "Tomate",
    notes: "RAS",
  },
];
